---
title: "Wine Classification Report"
author: "Martyna Pieczka, Magdalena Chamera"
format: pdf
editor: visual
---

## Wstęp

Celem niniejszego raportu jest podsumowanie trzech modeli klasyfikacyjnych utworzonych na podstawie danych *Wine recognition data*[^1], zawierającym 13 parametrów fizykochemicznych win powstałych z trzech typów winogron w tym samym regionie Włoch.

[^1]: Aeberhard, S. & Forina, M. (1992). Wine \[Dataset\]. UCI Machine Learning Repository. <https://doi.org/10.24432/C5PC7J>)

Oficjalna dokumentacji UCI nie podaje jednostek miar. Zbiór może jednak wciąż być używany do testowania metod klasyfikacji, zwłaszcza z powodu wykonanej standaryzacji (z-score) danych, co usuwa wpływ jednostek na wyniki algorytmów.

Źródła\
(a) Forina, M. et al, PARVUS - An Extendible Package for Data" Exploration, Classification and Correlation. Institute of Pharmaceutical" \[7\] " and Food Analysis and Technologies, Via Brigata Salerno, 16147 Genoa, Italy.\
(b) Stefan Aeberhard, email: stefan\@coral.cs.jcu.edu.au"\
(c) July 1991"

## Metodologia

## Analiza struktury danych Wine

## Interpretacja modeli

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
